### ISSUE TITLE
M1 build

### ISSUE THREAD

**Issue by papidb** [papidb/cpp-start#1]
```shell
gcc -pthread -std=c++14 -o main main.cpp
```

throws this on M1
```shell
Undefined symbols for architecture arm64:
  "dd::sum(int, int)", referenced from:
      _main in main-4460a7.o
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)", referenced from:
      _main in main-4460a7.o
  "std::__1::cout", referenced from:
      _main in main-4460a7.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dchima** [comment]
https://stackoverflow.com/questions/75469088/vs-code-undefined-symbols-for-architecture-arm64

**Comment by papidb** [comment]
> https://stackoverflow.com/questions/75469088/vs-code-undefined-symbols-for-architecture-arm64

I don't know where to put this, can you point me in the right direction?

**Comment by dchima** [comment]
can't be sure what you're doing but this error tends to mean you need to link all files needed for the compiler.

```
gcc onefile.cpp secondfile.cpp -o program
```

if it's just one file you're running, try

```
gcc main.cpp -o main
```

**Comment by metaclips** [comment]
> _main in main-4460a7.o
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(int)", referenced from:
      _main in main-4460a7.o

gcc is a C compiler so compiling C++ specific functions like cout will require using g++
```bash
g++ -o main main.cpp
```

> "dd::sum(int, int)", referenced from:
      _main in main-4460a7.o

🤮 C++ module system has to be the most confusing ever, probably due to inheriting C's features, they seem to want to try to get it right with C++20 I'd recommend you watch this video https://youtu.be/Kqo-jIq4V3I.
The issue here is that calling `gcc -o main main.cpp` imports only the `main.cpp` and `sum.h` file, since both files don't know about the sum.cpp function definitions it'll lead to undefined values, you would have to also add a `#include "sum.cpp"` to your main.cpp file before calling your `g++ -o main main.cpp` so that g++ know that there's a sum.cpp file and that it's included in the build

**Comment by papidb** [comment]
Thanks @dchima and @metaclips I was able to resolve it by importing `sum.cpp` in `main.cpp`.
